### ISSUE TITLE
PNG created doesn't keep CSS styling

### ISSUE THREAD

**Issue by MattBurn** [PfisterFactor/bear-equation-render#5]
Hi,

Needed something to write equations in bear app and this is a nice little tool. One thing I wanted though was the ability for the equation created to match my theme (Gotham) so I swapped out html2canvas to save-svg-as-png which allowed me to easily add a style to the svg before rendering.

I just read the other issue noting that you can import svg's into bear directly so I could always look into this.

I've also added a menu item that allows switching between AsciiMath, LaTex and MathML syntax in case you want something a bit more verbose with finer control, I have some other ideas that could turn this into a nice little tool.

I was wondering whether it is worth making a PR as it seems the codebase hasn't been touched in a while.

Matt

**Comment by PfisterFactor** [comment]
Hey thanks for using the app haha.

I wrote this tool to help take math notes on bear, but since then I have transitioned to using vim and a realtime latex renderer that I haven't put on github yet. I no longer use this tool (or bear) for my math notes but if you have a pull request ready to go I will approve it 👍.

If you would like to take over maintaining this repo as well let me know!
